server:
  port: 5002
spring:
  application:
    name: game-server-center
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/game_server_db
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

